### ISSUE TITLE
Create a README.md for atlas/ptoducers

### ISSUE THREAD

**Issue by Srijan-SS02** [InternetHealthReport/kafka-toolbox#17]
Create README.md file for atlas/producers directory specifying -
1. Requirements
2. Usage
3. Deprecated
Any other useful information will be appreciated.
For reference see [bgp/producers](https://github.com/InternetHealthReport/kafka-toolbox/blob/master/bgp/producers/README.md)

**Comment by romain-fontugne** [comment]
I have added the readme: https://github.com/InternetHealthReport/kafka-toolbox/tree/master/atlas/producers/README.md
