### ISSUE TITLE
Create README.md for peeringdb/producers 

### ISSUE THREAD

**Issue by Srijan-SS02** [InternetHealthReport/kafka-toolbox#19]
Create README.md file for peeringdb/producers directory specifying -

1. Requirements
2. Usage
3. Deprecated
Any other useful information will be appreciated.
For reference see [bgp/producers](https://github.com/InternetHealthReport/kafka-toolbox/blob/master/bgp/producers/README.md)

**Comment by romain-fontugne** [comment]
@m-appel can you take care of this one?

See the [bgp producer README](https://github.com/InternetHealthReport/kafka-toolbox/tree/master/bgp/producers) for an example.

**Comment by m-appel** [comment]
Fixed in 5b50b8b
