### ISSUE TITLE
ASes name in Kafka

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/kafka-toolbox#3]
- [x] Add a producer for AS names
- [ ] Consumers (e.g. psql/ASHegemony.py) should get names there

**Comment by ritikBhandari** [comment]
@romain-fontugne Can I take up this issue if possible?
Actually I have just learnt Kafka and this will help me sharpen my Kafka skills before the commencement of GSOC.

**Comment by romain-fontugne** [comment]
Sorry I think this is an old issue. We now handle this differently (https://github.com/InternetHealthReport/AS-names). So we don't really need this one anymore

**Comment by ritikBhandari** [comment]
Okay :(
